#!/usr/bin/env python3
import argparse
from logistics_gazebo_sim.worlds import write_worlds

parser = argparse.ArgumentParser()
parser.add_argument("output_dir")
args = parser.parse_args()
for path in write_worlds(args.output_dir):
    print(path)
