#!/usr/bin/env python3
import argparse
import os
from logistics_gazebo_sim.worlds import write_worlds, render_outdoor_world

parser = argparse.ArgumentParser()
parser.add_argument("output_dir")
args = parser.parse_args()
for path in write_worlds(args.output_dir):
    print(path)
outdoor = os.path.join(args.output_dir, "outdoor_logistics.world")
with open(outdoor, "w", encoding="utf-8") as stream:
    stream.write(render_outdoor_world())
print(outdoor)
