#!/usr/bin/env python3
"""Plan and independently check an outdoor route without starting a mission."""
import argparse
import json
import os

import roslib.packages
import rospkg

from logistics_gazebo_sim.outdoor_route_planner import plan_outdoor_route
from logistics_gazebo_sim.worlds import OUTDOOR_LAYOUTS


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('world', choices=sorted(OUTDOOR_LAYOUTS))
    parser.add_argument('--output', help='optional JSON report path')
    parser.add_argument('--solve-seconds', type=float, default=3.0)
    args = parser.parse_args()
    package = rospkg.RosPack().get_path('logistics_gazebo_sim')
    executables = roslib.packages.find_node('logistics_gazebo_sim',
                                             'ompl_3d_planner')
    if not executables:
        parser.error('build ompl_3d_planner before route planning')
    report = plan_outdoor_route(args.world, os.path.join(package, 'worlds'),
                                executables[0], args.solve_seconds)
    if args.output:
        with open(args.output, 'w', encoding='utf-8') as stream:
            json.dump(report, stream, indent=2)
            stream.write('\n')
    print('{}: {} waypoints, {} m, independent check {}'.format(
        report['world'], report['waypoint_count'], report['route_length_m'],
        report['independent_clearance_check']['feasible']))


if __name__ == '__main__':
    main()
